name: Build Telegram Desktop (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Ninja & CMake
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - name: Set up MSVC Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          arch: 'win64_msvc2019_64'
          modules: 'qtimageformats'

      - name: Build & Install Ada URL
        shell: cmd
        run: |
          git clone --depth 1 https://github.com/ada-url/ada.git ada_src
          cmake -B ada_build -S ada_src -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:/libs/ada -DADA_TESTING=OFF -DADA_BENCHMARKS=OFF
          cmake --build ada_build --target install

      - name: Configure CMake
        shell: cmd
        run: |
          set BOOST_ROOT=C:\hostedtoolcache\windows\Boost\1.83.0\x86_64
          cmake -B build -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_PREFIX_PATH="D:/libs/ada;C:/hostedtoolcache/windows/Boost/1.83.0/x86_64" ^
            -DBOOST_ROOT="C:/hostedtoolcache/windows/Boost/1.83.0/x86_64" ^
            -DBoost_NO_SYSTEM_PATHS=OFF ^
            -DDESKTOP_APP_QT_VERSION=6 ^
            -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON ^
            -DDESKTOP_APP_DISABLE_DBUS_INTEGRATION=ON ^
            -DDESKTOP_APP_USE_PACKAGED_LAZY=OFF ^
            -DTDESKTOP_API_ID=17349 ^
            -DTDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb

      - name: Build Telegram Desktop
        shell: cmd
        run: |
          cmake --build build --config Release --target Telegram

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-Windows-x64
          path: build/bin/Telegram.exe
