name: Build Telegram Desktop (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          arch: 'win64_msvc2019_64'
          modules: 'qtimageformats qtsvg'

      - name: Install Ninja & CMake Tools
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - name: Set up MSVC Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        shell: cmd
        run: |
          cmake -B build -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DDESKTOP_APP_QT_VERSION=6 ^
            -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON ^
            -DDESKTOP_APP_USE_PACKAGED=OFF

      - name: Build Telegram Desktop
        shell: cmd
        run: |
          cmake --build build --config Release --target Telegram

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-Windows-x64
          path: build/bin/Telegram.exe
